# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11dd2e6c0b2af8258e9b2a6b569a6e9af67d9787e4fcf2c2ee518c00d716d53a8391039005dbea44d7ec03815907d0fb793856e030dee374bd55c7e686663d88

test:
  secret_key_base: e4d3ee664e34b73670548c575791e0c15dd82ce40c0baa60fc4fbd8016c14e186f7387512beacae28f6e18674ddfe7a2a13b877d20cf972860fd2cc4d6b1a240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
